- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Configure Nginx server
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'

- name: Configure Nginx server config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify: restart nginx

- name: Enable and start Nginx
  service:
    name: nginx
    state: started
    enabled: yes
